"use client"

import type { NextPage } from 'next';
import Head from 'next/head';
import styled from 'styled-components';

// Styled Components for content pages
const ContentContainer = styled.div`
  max-width: 800px;
  margin: 0 auto;
  padding: 4rem 1.5rem; /* Adjust padding as needed */
  background-color: ${({ theme }) => theme.cardBg}; /* Use theme for background */
  border-radius: 1rem;
  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.1);
  margin-bottom: 4rem; /* Spacing from footer */
`;

const Title = styled.h1`
  font-size: 2.5rem;
  font-weight: bold;
  color: ${({ theme }) => theme.text};
  margin-bottom: 2rem;
  text-align: center;
`;

const Subtitle = styled.h2`
  font-size: 1.75rem;
  font-weight: bold;
  color: ${({ theme }) => theme.text};
  margin-top: 2rem;
  margin-bottom: 1rem;
`;

const Paragraph = styled.p`
  font-size: 1rem;
  line-height: 1.6;
  color: ${({ theme }) => theme.subtleText};
  margin-bottom: 1rem;
`;

const List = styled.ul`
  list-style: disc;
  margin-left: 1.5rem;
  margin-bottom: 1rem;
`;

const ListItem = styled.li`
  font-size: 1rem;
  line-height: 1.6;
  color: ${({ theme }) => theme.subtleText};
  margin-bottom: 0.5rem;
`;

const PrivacyPolicyPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Privacy Policy - WaveForm</title>
        <meta name="description" content="WaveForm&apos;s Privacy Policy outlining data collection and usage practices." />
      </Head>
      <ContentContainer>
        <Title>Privacy Policy</Title>
        <Paragraph>
          Last updated: July 24, 2025
        </Paragraph>
        <Paragraph>
          This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
        </Paragraph>
        <Paragraph>
          We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
        </Paragraph>

        <Subtitle>Interpretation and Definitions</Subtitle>
        <Paragraph>
          The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
        </Paragraph>

        <Subtitle>Definitions</Subtitle>
        <List>
          <ListItem>
            <strong>Application</strong> means the software program provided by the Company downloaded by You on any electronic device, named WaveForm.
          </ListItem>
          <ListItem>
            <strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to WaveForm, operated by Vegar Lee Berentsen.
          </ListItem>
          <ListItem>
            <strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.
          </ListItem>
          <ListItem>
            <strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.
          </ListItem>
          <ListItem>
            <strong>Service</strong> refers to the Application.
          </ListItem>
          <ListItem>
            <strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service.
          </ListItem>
          <ListItem>
            <strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
          </ListItem>
          <ListItem>
            <strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.
          </ListItem>
        </List>

        <Subtitle>Collecting and Using Your Personal Data</Subtitle>
        <Subtitle>Types of Data Collected</Subtitle>

        <h3>Personal Data</h3>
        <Paragraph>
          While using Our Service, We do not collect any personal identifying information directly from You. All your music library data, playlists, and preferences are stored locally on your device.
        </Paragraph>

        <h3>Usage Data</h3>
        <Paragraph>
          Usage Data is collected automatically when using the Service.
        </Paragraph>
        <Paragraph>
          Usage Data may include information such as Your Device&apos;s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data. This data is used solely for the purpose of app improvement and debugging, and is anonymized where possible.
        </Paragraph>

        <h3>iCloud Sync</h3>
        <Paragraph>
          WaveForm leverages Apple&apos;s iCloud for seamless synchronization of your music library data (playlists, saved songs metadata) across your Apple devices. This process is handled entirely by Apple&apos;s secure infrastructure using end-to-end encryption. We do not have access to the contents of your iCloud data. Downloaded audio files are stored locally on each device and are not synced via iCloud to preserve user storage.
        </Paragraph>

        <Subtitle>Information from Third-Party Services</Subtitle>
        <Paragraph>
          The Service utilizes content and services provided by YouTube Music. Your interaction with music content (playback, search) is facilitated through YouTube Music&apos;s APIs. Please refer to YouTube&apos;s (Google&apos;s) Privacy Policy for information on how they handle data related to your use of their services.
        </Paragraph>
        <Paragraph>
          Payments for premium features are processed via Apple&apos;s App Store (StoreKit). Your payment information and subscription status are managed by Apple. We do not collect or store your payment details.
        </Paragraph>

        <Subtitle>Use of Your Personal Data</Subtitle>
        <Paragraph>The Company may use Personal Data for the following purposes:</Paragraph>
        <List>
          <ListItem>
            <strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.
          </ListItem>
          <ListItem>
            <strong>To manage Your Account:</strong> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.
          </ListItem>
          <ListItem>
            <strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application&apos;s push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.
          </ListItem>
          <ListItem>
            <strong>For other purposes</strong>: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.
          </ListItem>
        </List>

        <Subtitle>Retention of Your Personal Data</Subtitle>
        <Paragraph>
          The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
        </Paragraph>

        <Subtitle>Disclosure of Your Personal Data</Subtitle>
        <Paragraph>We do not share your personal data with any third parties, except as required by law or to provide the Service (e.g., through Apple&apos;s iCloud and App Store services, and interaction with YouTube Music APIs).</Paragraph>

        <Subtitle>Security of Your Personal Data</Subtitle>
        <Paragraph>
          The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
        </Paragraph>

        <Subtitle>Changes to this Privacy Policy</Subtitle>
        <Paragraph>
          We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page. You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
        </Paragraph>

        <Subtitle>Contact Us</Subtitle>
        <Paragraph>
          If you have any questions about this Privacy Policy, You can contact us:
        </Paragraph>
        <List>
          <ListItem>By email: designr.pros@gmail.com</ListItem>
        </List>
      </ContentContainer>
    </>
  );
};

export default PrivacyPolicyPage;